module.exports = {
    API_ROOT_URL: process.env.API_ROOT_URL,
    DATABASE_CONNECTION_STRING: process.env.DATABASE_CONNECTION_STRING,
    ROOT_ADMIN_DISPLAY_NAME: process.env.ROOT_ADMIN_DISPLAY_NAME,
    ROOT_ADMIN_EMAIL_ADDRESS: process.env.ROOT_ADMIN_EMAIL_ADDRESS,
    ROOT_ADMIN_PASSWORD: process.env.ROOT_ADMIN_PASSWORD
};
